import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from ddgs import DDGS  # <--- UPDATED IMPORT
from google import genai
from datetime import datetime

# --- CONFIGURATION (Loaded from GitHub Secrets) ---
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
EMAIL_SENDER = os.environ.get("EMAIL_SENDER")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")
EMAIL_RECEIVER = os.environ.get("EMAIL_RECEIVER")

# Initialize Gemini
client = genai.Client(api_key=GEMINI_API_KEY)

def get_targeted_news():
    """Performs multiple targeted searches to ensure coverage of all regions."""
    print("🕵️ FINTEL Agent: Scouting global markets...")
    
    # We define specific search queries to ensure we don't miss niche markets
    queries = [
        "US Stock Market News latest trends",
        "Hong Kong Hang Seng Index financial news",
        "Nikkei 225 Japan market update",
        "Singapore STI index financial news",
        "Indonesia IDX Composite market news",
        "Global Geopolitical news impact on markets",
        "Global Supply Chain disruption news",
        "Emerging Market Trends financial analysis"
    ]
    
    aggregated_results = []
    
    # We use a context manager for DDGS
    with DDGS() as ddgs:
        for q in queries:
            try:
                # Fetch top 3 results per topic to keep the context window manageable but relevant
                results = ddgs.news(q, region="wt-wt", safesearch="off", max_results=3)
                if results:
                    for r in results:
                        # Format: [Topic] Title - Snippet
                        aggregated_results.append(f"[{q}] {r['title']} - {r['body']} (Source: {r['source']})")
            except Exception as e:
                print(f"⚠️ Error searching for {q}: {e}")
                
    return "\n\n".join(aggregated_results)

def analyze_and_write(raw_data):
    """Uses Gemini to synthesize the disparate news into a cohesive report."""
    print("🧠 FINTEL Agent: Analyzing data patterns...")
    
    prompt = f"""
    You are FINTEL, a high-level financial intelligence agent.
    
    Your goal is to write a concise, executive-level newsletter based on the raw news below.
    
    STRUCTURE:
    1. **Global Market Pulse**: A 2-sentence summary of the overall market mood (Bullish/Bearish/Uncertain).
    2. **Regional Highlights**:
       - US & Americas
       - Asia-Pacific (Focus on HK, Nikkei, SG, Indonesia)
    3. **Critical Intel**:
       - Geopolitics & Supply Chain (Only include if there is significant news)
       - Market Trends (Emerging patterns)
    
    STYLE:
    - Professional, objective, and dense with information.
    - Use bullet points.
    - If a specific region (e.g., Indonesia) has no significant news in the raw data, omit it rather than hallucinating.
    - Always include the source name in brackets, e.g., (Bloomberg).
    
    RAW DATA:
    {raw_data}
    """
    
    response = client.models.generate_content(
        model='gemini-1.5-flash', # <--- USING STABLE MODEL
        contents=prompt
    )
    return response.text

def send_newsletter(content):
    """Sends the formatted HTML email."""
    print("📧 FINTEL Agent: Dispatching intelligence report...")
    
    msg = MIMEMultipart()
    msg['From'] = EMAIL_SENDER
    msg['To'] = EMAIL_RECEIVER
    msg['Subject'] = f"FINTEL Digest: {datetime.now().strftime('%Y-%m-%d %H:00')}"

    # Convert Markdown to a simple HTML representation for better email readability
    html_content = f"""
    <html>
      <body>
        <h2>FINTEL Intelligence Report</h2>
        <pre style="font-family: Arial, sans-serif; white-space: pre-wrap;">{content}</pre>
        <hr>
        <small>Generated by Gemini 1.5 Flash • Automated via GitHub Actions</small>
      </body>
    </html>
    """
    
    msg.attach(MIMEText(html_content, 'html'))

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.send_message(msg)
        print("✅ Dispatch Successful.")
    except Exception as e:
        print(f"❌ Dispatch Failed: {e}")

if __name__ == "__main__":
    if not GEMINI_API_KEY:
        print("❌ Error: GEMINI_API_KEY not found in environment variables.")
        exit(1)
        
    news_data = get_targeted_news()
    if not news_data:
        print("⚠️ No news found. Skipping email.")
    else:
        newsletter = analyze_and_write(news_data)
        send_newsletter(newsletter)